en_dataset: rajpurkar/squad
en_dataset_config: ""
vi_dataset: taidng/UIT-ViQuAD2.0
vi_dataset_config: ""
output_dir: data
cache_dir: ""
seed: 42
validation_ratio: 0.1
stage1_vi_ratio: 0.5
allow_oversample: false

filtered_sample_seed: 42
en_train_size: 30000
en_validation_size: 5000
en_test_size: 5000
vi_train_size: 
vi_validation_size: 5000
vi_test_size: 
